title: Thi Thuy Dung Nguyen
logo: "/images/logo-small.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. candidate in Accounting at the Universidad Carlos III de Madrid
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/thi-thuy-dung-nguyen-345844214//">View My LinkedIn Profile</a> 
  <a href="https://github.com/dnguyen-td">View My GitHub Profile</a> 

  

theme: jekyll-theme-minimal
