project:
  type: website
  output-dir: docs

website:
  title: "Jun Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

