---
title: "Research"
---

`r fontawesome::fa("book-open", fill = "#124559", a11y = "sem")` **Client-level exposure to cryptocurrency and auditor responses** (***with Beatriz García Osma and Hoang Nhan Ha***)

Auditors increasingly face issues that transcend the formal boundaries of the firm. In an era of technological revolution and in settings where authoritative accounting and auditing guidance is yet to develop, auditors often lack the necessary knowledge and expertise to navigate novel and complex issues. In this study, we examine auditor responses to such uncertainty due to exposure associated with cryptocurrency. Cryptocurrency is of interest due to its fast growth and the lack of regulation on how to account for and audit crypto assets. Using Item 1 and Item 1A of 10-K filings, we construct and validate a novel text-based measure of client-level exposure to cryptocurrency and the nature of such exposure. Using this proxy, we provide evidence of the association of a client's exposure to cryptocurrency and audit pricing and auditor decisions.

`r fontawesome::fa("book-open", fill = "#124559", a11y = "sem")` **Opinion selling and auditor reputation** (***with Beatriz García Osma and Encarna Guillamon-Saorin***)

We study whether opinion selling damages auditors' reputation. We define opinion selling as cases where, either intentionally or unintentionally, the auditor gives the favorable audit opinion sought out by an opinion shopping client. Opinion shopping has raised long-standing concerns from policy setters. While prior literature focuses on the impacts of opinion shopping on clients, studies on the influences of opinion selling on auditors remain under-researched. Following Lennox (2000)'s approach, we identify successful opinion shopping clients and propose different proxies for lenient auditors who acquiesce to clients' proposals (intentionally or unwittingly). Our empirical results suggest that audit office opinion selling is associated with a subsequent reduction in market share. More lenient audit offices are not more likely to gain clients than stricter ones but are significantly more likely to lose existing clients. Moreover, we find evidence that the visibility of audit office opinion selling influences subsequent audit market penalties when the accumulated number of opinion shoppers captures visibility in a given office over the years.

`r fontawesome::fa("book-open", fill = "#124559", a11y = "sem")` **Audit materiality and debt contracting** (***with Beatriz García Osma and Encarna Guillamon-Saorin, and Omar De Ines Anton***)

We examine whether lenders influence audit materiality disclosures and their consequences over debt contracting. We run our tests on a hand-collected sample of materiality disclosures prepared by auditors of listed firms in the U.K. and Ireland from 2013 to 2020. We predict and find evidence that lenders penalize firms with higher audit materiality. Consistent with lenders facing asymmetric payoffs, we also document that lenders' demand for audit materiality is asymmetric: materiality adjusts faster in reaction to increases in client business risk than equivalent decreases. Our evidence is consistent with lenders being sophisticated users of the new extended audit reports. In particular, our evidence suggests that lenders consider audit materiality jointly with audit fees when making their screening and monitoring decisions.

`r fontawesome::fa("book-open", fill = "#124559", a11y = "sem")` **When auditors talk, who listens? Evidence from podcast series** (***with Hoang Nhan Ha***)

Initial stage research
